/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JDesktopPane;
import java.util.GregorianCalendar;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author Jose Luis Huertas Ch
 */
public class frmMenu extends javax.swing.JFrame implements Runnable {

    String hora, minutos, segundos;
    Thread hilo;
    
    public static JDesktopPane jDesktopPane_Menu;
    //public static JPanel escritorio;

    /**
     * Creates new form frmMenu
     */
    public frmMenu() {
        initComponents();
        //this.setResizable(false); // metodo para evitar que el usuario cambie el tamaño de la interfaz grafica
        this.setSize(new Dimension(1200, 700));
        //this.setSize(new Dimension(1366, 768));

        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null); //Centrar el formulario

        this.setLayout(null);

        //configuracion para un JPANEL
//        escritorio = new JPanel();
//        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
//        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
//        this.escritorio.setBounds(0, 0, ancho, (alto - 100));
//        this.add(escritorio);

        //configuracion para un JFRAMEINTERNAL
        jDesktopPane_Menu = new JDesktopPane();
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        this.jDesktopPane_Menu.setBounds(0, 0, ancho, (alto - 100));
        this.add(jDesktopPane_Menu);

        //hora
        hilo = new Thread(this);
        hilo.start();
    }

    public void hora() {

        Calendar calendario = new GregorianCalendar();
        Date horaActual = new Date();
        calendario.setTime(horaActual);
        hora = calendario.get(Calendar.HOUR_OF_DAY) > 9 ? "" + calendario.get(Calendar.HOUR_OF_DAY) : "0" + calendario.get(Calendar.HOUR_OF_DAY);
        minutos = calendario.get(Calendar.MINUTE) > 9 ? "" + calendario.get(Calendar.MINUTE) : "0" + calendario.get(Calendar.MINUTE);
        segundos = calendario.get(Calendar.SECOND) > 9 ? "" + calendario.get(Calendar.SECOND) : "0" + calendario.get(Calendar.SECOND);

    }

    @Override
    public void run() {
        Thread current = Thread.currentThread();

        while (current == hilo) {
            hora();
            lblTiempo.setText(hora + ":" + minutos + ":" + segundos);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        lblTiempo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_Cuartos = new javax.swing.JMenu();
        jMenuItem_Empleados = new javax.swing.JMenuItem();
        jMenuItem_Pacientes = new javax.swing.JMenuItem();
        jMenuItem_Cuartos = new javax.swing.JMenuItem();
        jMenuItem_Medicamentos = new javax.swing.JMenuItem();
        jMenuItem_Servicio = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTiempo.setFont(new java.awt.Font("AR CHRISTY", 3, 18)); // NOI18N
        lblTiempo.setForeground(new java.awt.Color(255, 255, 255));
        lblTiempo.setText("00:00:00");

        jMenu_Cuartos.setText("Mantenimiento");
        jMenu_Cuartos.setMaximumSize(new java.awt.Dimension(150, 50));
        jMenu_Cuartos.setMinimumSize(new java.awt.Dimension(150, 50));
        jMenu_Cuartos.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem_Empleados.setText("Empleados");
        jMenuItem_Empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_EmpleadosActionPerformed(evt);
            }
        });
        jMenu_Cuartos.add(jMenuItem_Empleados);

        jMenuItem_Pacientes.setText("Clientes");
        jMenuItem_Pacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_PacientesActionPerformed(evt);
            }
        });
        jMenu_Cuartos.add(jMenuItem_Pacientes);

        jMenuItem_Cuartos.setText("Cuartos");
        jMenuItem_Cuartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_CuartosActionPerformed(evt);
            }
        });
        jMenu_Cuartos.add(jMenuItem_Cuartos);

        jMenuItem_Medicamentos.setText("Productos");
        jMenuItem_Medicamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_MedicamentosActionPerformed(evt);
            }
        });
        jMenu_Cuartos.add(jMenuItem_Medicamentos);

        jMenuItem_Servicio.setText("Servicios");
        jMenuItem_Servicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ServicioActionPerformed(evt);
            }
        });
        jMenu_Cuartos.add(jMenuItem_Servicio);

        jMenuBar1.add(jMenu_Cuartos);

        jMenu2.setText("Hospitalizacion");
        jMenu2.setPreferredSize(new java.awt.Dimension(150, 50));
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Registro de consumo");
        jMenu3.setPreferredSize(new java.awt.Dimension(150, 50));
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Control de Pago");
        jMenu4.setPreferredSize(new java.awt.Dimension(150, 50));
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Reporte");
        jMenu5.setPreferredSize(new java.awt.Dimension(150, 50));
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 1286, Short.MAX_VALUE)
                .addComponent(lblTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTiempo)
                .addContainerGap(689, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_EmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_EmpleadosActionPerformed

        vistaMantEmpleados vistaEmpleado = new vistaMantEmpleados();
        jDesktopPane_Menu.add(vistaEmpleado);
        Dimension desktopSize = jDesktopPane_Menu.getSize();
        Dimension FrameSize = vistaEmpleado.getSize();
        vistaEmpleado.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        vistaEmpleado.setVisible(true);
    }//GEN-LAST:event_jMenuItem_EmpleadosActionPerformed

    private void jMenuItem_PacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_PacientesActionPerformed
        // TODO add your handling code here:
//        vistaMantPacientes vistaPaciente = new vistaMantPacientes();
//        jDesktopPane_Menu.add(vistaPaciente);
//        Dimension desktopSize = jDesktopPane_Menu.getSize();
//        Dimension FrameSize = vistaPaciente.getSize();
//        vistaPaciente.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
//        vistaPaciente.setVisible(true);
    }//GEN-LAST:event_jMenuItem_PacientesActionPerformed

    private void jMenuItem_CuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_CuartosActionPerformed
        // TODO add your handling code here:
       vistaCuartos verCuartos = new vistaCuartos();
        jDesktopPane_Menu.add(verCuartos);
        Dimension desktopSize = jDesktopPane_Menu.getSize();
        Dimension FrameSize = verCuartos.getSize();
        verCuartos.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        verCuartos.setVisible(true);

    }//GEN-LAST:event_jMenuItem_CuartosActionPerformed


    private void jMenuItem_MedicamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_MedicamentosActionPerformed
        // TODO add your handling code here:
//        vistaMantMedicamentos vistaMedicamento = new vistaMantMedicamentos();
//        jDesktopPane_Menu.add(vistaMedicamento);
//        Dimension desktopSize = jDesktopPane_Menu.getSize();
//        Dimension FrameSize = vistaMedicamento.getSize();
//        vistaMedicamento.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
//        vistaMedicamento.setVisible(true);
    }//GEN-LAST:event_jMenuItem_MedicamentosActionPerformed

    private void jMenuItem_ServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ServicioActionPerformed
        // TODO add your handling code here:
//        vistaMantServicio vistaServicio = new vistaMantServicio();
//        jDesktopPane_Menu.add(vistaServicio);
//        Dimension desktopSize = jDesktopPane_Menu.getSize();
//        Dimension FrameSize = vistaServicio.getSize();
//        vistaServicio.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
//        vistaServicio.setVisible(true);
    }//GEN-LAST:event_jMenuItem_ServicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new frmMenu().setVisible(true);
                //se coloco esto para ver el jpanel
                new frmMenu().setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem_Cuartos;
    private javax.swing.JMenuItem jMenuItem_Empleados;
    private javax.swing.JMenuItem jMenuItem_Medicamentos;
    private javax.swing.JMenuItem jMenuItem_Pacientes;
    private javax.swing.JMenuItem jMenuItem_Servicio;
    private javax.swing.JMenu jMenu_Cuartos;
    private javax.swing.JLabel lblTiempo;
    // End of variables declaration//GEN-END:variables

}
